openapi: 3.0.0
info:
  title: Onboarding 
  version: "1.2"
  description: STD22034
servers : 
- url: https://STD22034.com
paths:
  /student:
    get:
      description: Get a student
      responses:
        '200':
          description: Student found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/student"
    post:
      operationId: createStudent
      description: Create a new student
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  default : 1
                name:
                  type: string
                  default : "Kaïl"
                birthdate:
                  type: string
                  default: "29/02/2004"
      responses:
        '201':
          description: Student created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/student"
        '400':
          description: Bad request
components:
  schemas:
    student:
      type: object
      properties:
        id:
          type: integer
          default : 1
        name:
          type: string
          default : Kaïl
        birthdate:
          type: string
          default : "29/02/2004"